//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAMetrics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectMetric
    {
        public int ID { get; set; }
        public string Project { get; set; }
        public string Application { get; set; }
        public Nullable<int> AgeWeek { get; set; }
        public Nullable<int> AgeBiWeek { get; set; }
        public Nullable<int> AgeThreeMonth { get; set; }
        public Nullable<int> AgeOther { get; set; }
    }
}
