//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAMetrics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionMetricsCycle
    {
        public int ID { get; set; }
        public string Project { get; set; }
        public string Release { get; set; }
        public string ReleaseCycle { get; set; }
        public Nullable<System.DateTime> ReleaseCycleStartDate { get; set; }
        public Nullable<System.DateTime> ReleaseCycleEnddate { get; set; }
        public string Application { get; set; }
        public Nullable<int> TotalTestInstances { get; set; }
        public Nullable<int> PassedTestInstances { get; set; }
        public Nullable<int> FailedTestInstances { get; set; }
        public Nullable<int> NotCompletedTestInstances { get; set; }
        public Nullable<int> BlockedTestInstances { get; set; }
        public Nullable<int> NoRunTestInstances { get; set; }
        public Nullable<decimal> PercentTotalInstancesPassed { get; set; }
        public Nullable<decimal> PercentTotalInstancesFailed { get; set; }
        public Nullable<int> TotalFirstTimeRuns { get; set; }
        public Nullable<int> TotalFirstTimePassedRuns { get; set; }
        public Nullable<int> TotalFirstTimeFailedRuns { get; set; }
        public Nullable<int> TotalRuns { get; set; }
        public Nullable<int> TotalPassedRuns { get; set; }
        public Nullable<int> TotalFailedRuns { get; set; }
        public Nullable<int> TotalReRuns { get; set; }
        public Nullable<int> TotalReRunPassed { get; set; }
        public Nullable<int> TotalReRunFailed { get; set; }
        public Nullable<decimal> PercentFirstRunPassed { get; set; }
        public Nullable<decimal> PercentFirstRunFailed { get; set; }
        public Nullable<decimal> PercentageTotalRunsPassed { get; set; }
        public Nullable<decimal> PercentageTotalRunsFailed { get; set; }
        public Nullable<decimal> PercentageReRunPassed { get; set; }
        public Nullable<decimal> PercentageReRunFailed { get; set; }
        public Nullable<int> ReleaseCycleId { get; set; }
    }
}
