//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAMetrics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ls_dashboardEntities : DbContext
    {
        public ls_dashboardEntities()
            : base("name=ls_dashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<DataRefresh> DataRefreshes { get; set; }
        public virtual DbSet<Cycle> Cycles { get; set; }
        public virtual DbSet<DefectMetric> DefectMetrics { get; set; }
        public virtual DbSet<WeeklyExecutionMetric> WeeklyExecutionMetrics { get; set; }
        public virtual DbSet<WeeklyExecutionMetricsDetailed> WeeklyExecutionMetricsDetaileds { get; set; }
        public virtual DbSet<WeeklyExecutionMetricsProgramInit> WeeklyExecutionMetricsProgramInits { get; set; }
    }
}
