//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAMetrics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyExecutionMetricsDetailed
    {
        public int ID { get; set; }
        public string WeekStartDate { get; set; }
        public string WeekEndDate { get; set; }
        public int CalenderWeek { get; set; }
        public string Project { get; set; }
        public string Application { get; set; }
        public string ProgramInitiative { get; set; }
        public string ReleaseCycle { get; set; }
        public string TestSet { get; set; }
        public int TestInstanceId { get; set; }
        public int TestId { get; set; }
        public string TestName { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
    }
}
